language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
jobs:
  include:
    - stage: test & cover
      node_js: 10
      script:
        - npm run cover
        - npm run coverage
    - stage: test in web browser
      node_js: 10
      script:
        - npm run test:browser
      addons:
        apt:
          packages:
            - xvfb
      install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - npm install
    - stage: test types
      node_js: 10
      script:
      - npm run test:types
    - stage: test documentation
      node_js: 10
      script:
        - npm run test:docs
      install:
        - cd docs && bundle install --path ./vendor/bundle
